slogan: “红炉点雪”
email: 523897704@qq.com
logo: "/images/logo.svg"

mathjax: false # 加载 LateX 数学公式库

favicon: # 配置网页图标
  small: /images/favicon-16x16.png
  medium: /images/favicon-32x32.png
  apple_touch_icon: /images/apple-touch-icon.png
  safari_pinned_tab: /images/logo.svg

subpage: # 开启“子页”功能，详见 README
  enable: true
  pages:
    - name: learn
      path: learn
      title: 学习
      icon: /images/icon/icon-code.svg
      description: 记录一些学习的小碎片
    - name: course
      path: course
      title: 教程
      icon: /images/icon/icon-book.svg
      description: 记录一些生活工作中的小技巧
    - name: life
      path: life
      title: 生活
      icon: /images/icon/life.svg
      description: 记录一点生活

index: # 配置首页个性化内容
  motto: "我们站着，不说话，就十分美好。"
  poem:
    - 草在结它的种子
    - 风在摇它的叶子
  photo: /images/about.jpg
  about:
    title: 关于
    text:
      - 我走了很久很久来这里找你玩
      - 可是你不在家
      - 那我现在回去啦

foot:
  title:
    - "人生如此"
    - "拿酒来"


reward: # 赞赏
  enable: true
  face: /images/assets/author-face.jpg # 头像图片
  paycode: /images/assets/pay-code.jpg # 支付码图片
  text: “给作者倒杯卡布奇诺”
  btnText: 喜欢作者

# see https://github.com/gitalk/gitalk
gitalk: # gitalk 评论
  enable: false
  owner: # MUST HAVE, Your Github Username
  admin:
  repo: # MUST HAVE, The name of the repo you use to store Gitment comments
  clientID: # MUST HAVE, Github client id for the Gitment
  clientSecret: # EITHER this or proxy_gateway, Github access secret token for the Gitment

  distractionFreeMode: false # Facebook-like distraction free mode
  # When the official proxy is not available, you can change it to your own proxy address
  proxy: https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token # This is official proxy adress
  # Gitalk's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en | es-ES | fr | ru | zh-CN | zh-TW
  language: zh-CN

# see https://github.com/tea3/hexo-related-popular-posts
related_post:
  enable: false
  config:
    maxCount: 5 # Maximum count of a list. default 5
    ulClass: # Class name of element. deafult 'popular-posts'
    PPMixingRate: 0.4 # Mixing ratio of popular posts and related posts. default 0.0(=Related posts only)
    isDate: # visible the date. false
    isImage: # visible the image. false
    isExcerpt: # visible the excerpt. false
    PPCategoryFilter: # Option to fix category on Popular Posts. undefined
    PPTagFilter: # Option to fix tag on Popular Posts. undefined

# Baidu Webmaster tools verification.
# See: https://ziyuan.baidu.com/site
baidu_site_verification:

# Baidu Analytics
# See: https://tongji.baidu.com
baidu_analytics: # <app_id>

# 自定义字体，用于美化部分汉字的显示效果.
# 可以通过替换 _font/ 目录下的字体文件替换自己喜欢的字体
zh_font:
  enable: true
  fontName: sourceHanSerif
  type: ttf
  style:
    - normal
    - bold

# 配置时间线 参考
timeline:
  enable: false
  order: false # 是否按时间正序展示，false 为倒序
  items:
    - name: article
      color: "#ee936c"
      icon: /images/icon/icon-article.svg
      checked: false
    - name: app
      color: "#60a465"
      icon: /images/icon/icon-app.svg
      checked: true
    - name: event
      color: "#568dc4"
      icon: /images/icon/icon-event.svg
      checked: false

# 标签云
tagcloud:
  fancy: true
  min_font: 14
  max_font: 30

mermaid:
  enable: true # 启用 Mermaid 增强
  version: latest
  options:
    startOnload: true


search:
  path: search.json
  enable: true
  field: post
  content: true
